{-# LANGUAGE GHC2021, TemplateHaskell #-}

-- | This module is autogenerated by Foreign.Swift.SetupHooks to export a
-- handful of functions that need to be exported across the FFI boundary to
-- Swift in order to implement FFI wrapper internals.
--
-- Do not edit!
module Foreign.Swift.Exported.Utils where

import qualified Foreign.Ptr as Ptr
import qualified Foreign.Marshal as Ptr
import qualified Foreign.StablePtr as Ptr

import Foreign.Swift
import Foreign.Swift.Marshal

-- No need, just use `free` (compatible) and `hs_free_stable_pointer` (from the RTS)

-- -- | 'Ptr.freeStablePtr'
-- freeStablePtr :: Ptr.StablePtr () -> IO ()
-- freeStablePtr = Ptr.freeStablePtr
--
-- -- | 'Ptr.free'
-- free :: Ptr.Ptr () -> IO ()
-- free = Ptr.free
--
-- $(foreignExportSwift 'freeStablePtr)
-- $(foreignExportSwift 'free)

